### ISSUE TITLE
Upload to the eCloud

### ISSUE THREAD

**Issue by PiggyPiglet** [IntellectualSites/PlotSquared-Expansion#3]
This expansion should be uploaded to the eCloud for easy access by users. You can sign up [here](https://api.extendedclip.com/home/), and a moderator will verify the expansion when they see it, which will allow any server with placeholderapi installed to download the expansion via `/papi ecloud download PlotSquared`.

**Comment by NotMyFault** [comment]
Just uploaded, thanks for notifying us :)
