### ISSUE TITLE
Placeholder request: Plot Id

### ISSUE THREAD

**Issue by leonardo-dgs** [IntellectualSites/PlotSquared-Expansion#4]
It would be useful to add the placeholder `plotsquared_currentplot_id_x` and `plotsquared_currentplot_id_y`

**Comment by leonardo-dgs** [comment]
@N0tMyFaultOG Why do you close this?

**Comment by NotMyFault** [comment]
Because I implemented it and closed the issue by referencing it to my commit.

**Comment by leonardo-dgs** [comment]
Thank you
